import React, { useState } from 'react';
import { OptimizedPackage } from '../types.ts';
import { 
  Sparkles, 
  Copy, 
  Check, 
  Film, 
  Hash, 
  FileText, 
  Scissors, 
  Clock, 
  Download,
  CheckCircle2
} from 'lucide-react';

interface OptimizedPackageViewProps {
  packageData: OptimizedPackage;
}

export const OptimizedPackageView: React.FC<OptimizedPackageViewProps> = ({ packageData }) => {
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleDownloadPlan = () => {
    const textContent = `VIRALYTICS AI - PRODUCTION EDIT PLAN
Generated by Team Go-Gitters

REWRITTEN HOOK:
${packageData.rewrittenHook}

OPTIMIZED CAPTION:
${packageData.improvedCaption}

HIGH-VELOCITY HASHTAGS:
${packageData.optimizedHashtags.join(' ')}

THUMBNAIL SPECIFICATION:
Text: ${packageData.thumbnailSuggestion.text}
Composition: ${packageData.thumbnailSuggestion.composition}
Contrast: ${packageData.thumbnailSuggestion.contrastRatio}

TIMELINE EDIT ACTIONS:
${packageData.editPlan.map(e => `[${e.timestamp}] Step ${e.step}: ${e.instruction}`).join('\n')}
`;

    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'viralytics_production_edit_plan.txt';
    a.click();
    URL.revokeObjectURL(url);
    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 2500);
  };

  return (
    <div className="glass-panel p-6 rounded-2xl border-white/10 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 border-b border-white/10 gap-3">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-cyan-400" />
            <h3 className="text-base font-bold text-white tracking-wide">
              Step 7: Production-Ready Optimized Version
            </h3>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Ready-to-deploy copy, thumbnail packaging, and concrete timeline edit cutlist.
          </p>
        </div>

        <button
          onClick={handleDownloadPlan}
          className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-cyan-500 hover:bg-cyan-400 text-black flex items-center gap-1.5 transition-colors self-start sm:self-auto shadow-sm"
        >
          {downloadSuccess ? (
            <>
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>Downloaded Plan!</span>
            </>
          ) : (
            <>
              <Download className="w-3.5 h-3.5" />
              <span>Export Edit Plan (.txt)</span>
            </>
          )}
        </button>
      </div>

      {/* Grid of Copy Assets */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Rewritten Hook */}
        <div className="p-4 rounded-xl bg-slate-900/80 border border-cyan-500/30 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-cyan-400 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              <span>1. Rewritten Viral Hook (0-5s)</span>
            </span>
            <button
              onClick={() => copyToClipboard(packageData.rewrittenHook, 'hook')}
              className="text-xs text-slate-400 hover:text-white flex items-center gap-1"
            >
              {copiedKey === 'hook' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'hook' ? 'Copied' : 'Copy'}</span>
            </button>
          </div>
          <p className="text-sm font-semibold text-white bg-black/40 p-3 rounded-lg border border-white/5 font-mono">
            &ldquo;{packageData.rewrittenHook}&rdquo;
          </p>
        </div>

        {/* Improved Caption */}
        <div className="p-4 rounded-xl bg-slate-900/80 border border-white/10 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-400 flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5" />
              <span>2. High-Retention Caption Copy</span>
            </span>
            <button
              onClick={() => copyToClipboard(packageData.improvedCaption, 'caption')}
              className="text-xs text-slate-400 hover:text-white flex items-center gap-1"
            >
              {copiedKey === 'caption' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'caption' ? 'Copied' : 'Copy'}</span>
            </button>
          </div>
          <p className="text-xs text-slate-200 bg-black/40 p-3 rounded-lg border border-white/5 leading-relaxed">
            {packageData.improvedCaption}
          </p>
        </div>
      </div>

      {/* Hashtags & Thumbnail Recommendation */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Hashtags */}
        <div className="p-4 rounded-xl bg-slate-900/80 border border-white/10 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-pink-400 flex items-center gap-1.5">
              <Hash className="w-3.5 h-3.5" />
              <span>3. Algorithmic High-Velocity Tags</span>
            </span>
            <button
              onClick={() => copyToClipboard(packageData.optimizedHashtags.join(' '), 'tags')}
              className="text-xs text-slate-400 hover:text-white flex items-center gap-1"
            >
              {copiedKey === 'tags' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'tags' ? 'Copied' : 'Copy'}</span>
            </button>
          </div>
          <div className="flex flex-wrap gap-1.5 pt-1">
            {packageData.optimizedHashtags.map((tag, i) => (
              <span
                key={i}
                className="text-xs font-mono font-medium px-2 py-1 rounded bg-pink-500/10 text-pink-300 border border-pink-500/20"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Thumbnail Spec */}
        <div className="p-4 rounded-xl bg-slate-900/80 border border-white/10 space-y-2">
          <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-1.5">
            <Film className="w-3.5 h-3.5" />
            <span>4. Mobile Thumbnail Packaging</span>
          </span>
          <div className="bg-black/40 p-2.5 rounded-lg border border-white/5 space-y-1 text-xs">
            <div className="text-white font-mono font-bold">
              Text: &ldquo;{packageData.thumbnailSuggestion.text}&rdquo;
            </div>
            <div className="text-slate-400 text-[11px]">
              {packageData.thumbnailSuggestion.composition}
            </div>
          </div>
        </div>
      </div>

      {/* Concrete Timeline Edit Plan */}
      <div className="space-y-3 pt-2 border-t border-white/5">
        <div className="flex items-center justify-between">
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-1.5">
            <Scissors className="w-3.5 h-3.5 text-cyan-400" />
            <span>Concrete Timeline Edit Plan (Editor Cutlist)</span>
          </h4>
          <span className="text-[11px] text-slate-500">
            FFmpeg / Premiere / CapCut ready
          </span>
        </div>

        <div className="space-y-2">
          {packageData.editPlan.map((step) => (
            <div
              key={step.step}
              className="flex items-start gap-3 p-3 rounded-xl bg-slate-900/60 border border-white/5 hover:border-cyan-500/30 transition-all text-xs"
            >
              <div className="w-6 h-6 rounded-lg bg-cyan-500/10 border border-cyan-500/20 text-cyan-300 font-mono font-bold flex items-center justify-center shrink-0">
                {step.step}
              </div>
              <div className="flex-1 space-y-0.5">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono font-semibold text-purple-300 flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    <span>{step.timestamp}</span>
                  </span>
                </div>
                <p className="text-slate-300 text-xs">
                  {step.instruction}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
